services:

  github-service:
    build: 
      context: ./github-service
      dockerfile: ./github-service.dockerfile
    restart: always
    ports:
      - "3000:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - rabbitmq
      - redis

  profiler-service:
    build: 
      context: ./profiler-service
      dockerfile: ./profiler-service.dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "3001:8081"
    
  rabbitmq:
    image: 'rabbitmq:3.12-management'
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "8000:5672" # RabbitMQ
      - "8001:15672" # Management interface
  
  redis:
    image: 'redis:7-alpine'
    ports:
      - "6379:6379"
  
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: "gitpulse"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:

  db-data:
