services:

  github-service:
    build: 
      context: ./github-service
      dockerfile: ./github-service.dockerfile
    restart: always
    ports:
      - "3000:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    # deploy:
    #   mode: replicated
    #   replicas: 1